### PR TITLE
fix "Varies with device" when get version

### PR DESCRIPTION
**Pull request by FozerZ**

### CODE REVIEW

**Review by mxdevadmin — APPROVED** [review]
Tested locally and it is working.

**Review by ademirqueiroga — COMMENTED** [review]
Also tested this fix and it is working as intended

**Comment by JoMingyu** [comment]
Thanks a lot. I'll release this asap.

**Comment by JoMingyu** [comment]
[update released at pypi](https://pypi.org/project/google-play-scraper/1.2.2/).

**Pull request merged**
