### PR TITLE
add permission-feature

### PR DESCRIPTION
**Pull request by kluhan**
adds feature to download permissions

### CODE REVIEW

**Comment by JoMingyu** [comment]
Is this PR in draft status? There is no contributing guide, so it is ambiguous to review. It's a very valuable contribution, so why don't you merge this PR and leave me to update the code?

**Comment by kluhan** [comment]
Sorry I'm new to Python. I saw some tests fail and I panicked a little. If you see some serious errors please let me know so I can fix them as best I can

**Comment by JoMingyu** [comment]
All is fine, how about merging this PR first and letting me fix the test fail? As I said, it is a very valuable PR, so I want to release it soon. And Python 3.3 to 3.5 will be ending support, so if you want to fix it yourself, you can ignore the tests for those versions.

> Sorry I'm new to Python. I saw some tests fail and I panicked a little. If you see some serious errors please let me know so I can fix them as best I can

**Comment by kluhan** [comment]
I updated two tests that failed due to changes to the relevant app.
I checked it through the postman so I hope it's fine

**Comment by JoMingyu** [comment]
> I updated two tests that failed due to changes to the relevant app.
> I checked it through the postman so I hope it's fine

Thanks! I'll merge this soon.

**Review by JoMingyu — APPROVED** [review]

**Comment by JoMingyu** [comment]
It serves after next version(0.2.2)

**Pull request merged**
